const fs=require('node:fs'),vm=require('node:vm');
const app=fs.readFileSync('assets/brand-v04/app-v05.js','utf8').split('function render()')[0];
const ctx={localStorage:{getItem:()=>null},document:{getElementById:()=>null}};vm.createContext(ctx);
vm.runInContext(app+';globalThis.build={home,company,research,contact,footer,nav,titleFor,descriptions,setLang:value=>lang=value}',ctx);
const b=ctx.build, original=fs.readFileSync('index.html','utf8');
const verification=[...original.matchAll(/<meta\b[^>]*name="(?:naver-site-verification|msvalidate.01|google-site-verification)"[^>]*>/g)].map(m=>m[0]).join('');
for(const [page,path] of Object.entries({index:'/',company:'/company',research:'/research',contact:'/contact',privacy:'/privacy',terms:'/terms'})){
 const legal=['privacy','terms'].includes(page),legalBody=legal?fs.readFileSync(`assets/brand-v04/${page}.html`,'utf8'):'';
 const main=legal?legalBody:b[page==='index'?'home':page]();const desc=b.descriptions[path][0],title=b.titleFor(path),url='https://biotrix.co.kr'+path;
 const nav=b.nav().map(([u,s])=>`<a href="${u}" ${u===path?'aria-current="page"':''}>${s}</a>`).join('');
 const html=`<!doctype html><html lang="ko"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#073E35"><title>${title}</title><meta name="description" content="${desc}">${verification}<link rel="canonical" href="${url}"><meta property="og:type" content="website"><meta property="og:site_name" content="BIOTRIX"><meta property="og:url" content="${url}"><meta property="og:title" content="${title}"><meta property="og:description" content="${desc}"><meta property="og:locale" content="ko_KR"><meta property="og:image" content="https://biotrix.co.kr/assets/brand-v04/assets/share-v05.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="BIOTRIX 한국바이오트릭스"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${title}"><meta name="twitter:description" content="${desc}"><meta name="twitter:image" content="https://biotrix.co.kr/assets/brand-v04/assets/share-v05.png"><link rel="icon" href="/assets/brand-v04/assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="/assets/brand-v04/style.css?v=ci05"><link rel="preload" href="/assets/brand-v04/assets/fonts/Pretendard-site-v05r1.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="/assets/brand-v04/typography-v05.css"><link rel="stylesheet" href="/assets/brand-v04/audit-v05.css"><script type="application/ld+json">${JSON.stringify({'@context':'https://schema.org','@type':'Organization',name:'BIOTRIX',url:'https://biotrix.co.kr/',logo:'https://biotrix.co.kr/assets/brand-v04/assets/logo-green-v05.svg',email:'andrew@biotrix.co.kr'})}</script></head><body class="${path==='/'?'is-home':''}"><a class="skip" href="#main">본문 바로가기</a><header><a href="/" class="brand" aria-label="BIOTRIX 홈"><img src="/assets/brand-v04/assets/logo-white-v05.svg" alt="BIOTRIX 한국바이오트릭스" width="837" height="195"></a><nav id="main-navigation" aria-label="주요 메뉴">${nav}</nav><button class="lang" aria-label="영어로 보기">EN</button><button class="menu" aria-label="메뉴 열기·닫기" aria-controls="main-navigation" aria-expanded="false"><span></span><span></span></button></header><main id="main" tabindex="-1"${legal?' class="legal-main"':''}>${main}</main>${legal?`<template id="legal-content">${legalBody}</template>`:''}<footer>${b.footer()}</footer><script src="/assets/brand-v04/app-v05.js?v=restore01" defer></script></body></html>`;
 fs.writeFileSync(page+'.html',html);
}
console.log('Built six static pages with approved copy');
