const fs=require('fs'),path=require('path');const root=path.resolve(__dirname,'..');
const bi=(en,ko,tag='p',cls='')=>`<${tag} class="bilingual ${cls}"><span lang="en">${en}</span><span lang="ko">${ko}</span></${tag}>`;
const link=(url,en,ko)=>`<a class="button" href="${url}">${bi(en,ko,'span')}</a>`;
const intro=(en,ko,e,k)=>`<section class="wrap page-intro">${bi(en,ko,'h1')}${bi(e,k,'p','intro-copy')}</section>`;
const fields=[
['enera','ENERA','Cellular energy & metabolism','세포 에너지·대사','Investigate how cellular energy metabolism relates to functional decline, and define interventions and functional measures for further evaluation.','세포의 에너지 대사와 기능 저하의 관계에 주목합니다. 기능을 유지하거나 개선하기 위한 접근과 이를 평가할 지표를 구체화합니다.','Energy metabolism, stress response and cell viability','에너지 대사, 스트레스 반응, 세포 생존','A defined cell model, functional endpoints and reproducible measurements','세포 모델 선정, 기능 평가 지표, 반복 측정의 재현성'],
['flora','FLORA','Microbes & microbiome','미생물·마이크로바이옴','Explore the functions of selected microbes and their metabolites, with attention to composition, stability and production conditions.','미생물과 대사산물의 기능을 연구하는 방향입니다. 유용한 균주와 물질을 선정하고 구성, 안정성, 생산 조건을 함께 검토합니다.','Strain characteristics, metabolites and host interactions','균주 특성, 대사산물, 인체와의 상호작용','Composition analysis, functional evaluation and batch consistency','성분 분석, 기능 평가, 배치 간 품질 일관성'],
['immera','IMMERA','Immune regulation','면역 조절','Explore approaches to excessive or imbalanced immune responses by defining a relevant pathway, cell type and desired response.','과도하거나 불균형한 면역 반응에 주목합니다. 대상 경로와 세포, 조절하려는 반응을 정하고 선택성과 안전성을 평가하는 방향입니다.','Immune pathways, response selectivity and metabolic context','면역 경로, 반응 선택성, 대사 환경','Relevant immune models, response measurements and safety evaluation','면역 모델 선정, 반응 측정, 안전성 평가'],
['renova','RENOVA','Cellular aging & tissue recovery','세포 노화·조직 회복','Examine age-related cellular changes and loss of tissue function, and evaluate approaches to maintaining or restoring function.','노화에 따른 세포 상태 변화와 조직 기능 저하에 주목합니다. 노화 관련 지표와 회복 반응을 평가하여 기능 유지와 회복을 위한 접근을 탐구합니다.','Cellular state, tissue environment and functional recovery','세포 상태, 조직 환경, 기능 회복','Relevant tissue models and functional endpoints beyond individual markers','조직 모델 선정, 개별 지표와 함께 평가할 기능 지표'],
['activa','ACTIVA','Bioproduction & process development','바이오 생산·공정 개발','Support development across the research areas by evaluating production yield, purity, stability, reproducibility and cost.','연구한 물질을 일정한 품질로 생산하기 위한 공통 기반입니다. 수율, 순도, 안정성, 공정 재현성과 비용을 함께 검토합니다.','Production process, quality and manufacturing economics','생산 공정, 품질, 제조 경제성','Process design, analytical methods, quality specifications and cost models','공정 설계, 분석 방법, 품질 규격, 원가 모델']];
const principles=[['Contribution to treatment and quality of life','치료와 삶의 질에 대한 기여','Define the problem, intended application and meaningful benefit before selecting an approach.','해결하려는 문제와 적용 대상을 정하고, 치료와 생활에 어떤 도움이 필요한지 구체화합니다.'],['Performance & reproducibility','기술 성능과 재현성','Evaluate function, selectivity and safety using appropriate models and repeatable measurements.','적합한 모델과 반복 가능한 측정으로 기능, 선택성, 안전성을 평가합니다.'],['Production & commercial feasibility','생산성과 사업화 가능성','Consider quality, yield, stability, cost and partner capabilities early in development.','개발 초기부터 품질, 수율, 안정성, 비용과 협력사의 역량을 함께 검토합니다.']];
const grid=()=>`<div class="principle-grid">${principles.map(a=>`<article>${bi(a[0],a[1],'h3')}${bi(a[2],a[3])}</article>`).join('')}</div>`;
const cta=()=>`<section class="contact-band"><div class="wrap contact-layout"><div>${bi('Technology & business collaboration','기술·사업 협력','h2')}</div><div>${bi('We welcome proposals for joint research, technology development, production, commercialization and investment discussions.','공동연구, 기술 개발, 생산·사업화 및 투자 관련 협력 제안을 기다립니다.')}${link('/contact','Contact BIOTRIX','협력 문의')}</div></div></section>`;
const cards=()=>`<div class="project-grid">${fields.map((a,i)=>`<a class="project-card project-${i}" href="/programs#${a[0]}"><div class="card-top"><span class="card-number">0${i+1}</span><span class="project-name">${a[1]}</span></div><div class="card-body">${bi(a[2],a[3],'h3')}${bi(a[4],a[5],'p','card-copy')}${bi('View development direction →','개발 방향 살펴보기 →','span','card-action')}</div></a>`).join('')}</div>`;
const direction=bi('BIOTRIX aims to expand treatment options through biopharmaceutical and technology development. We focus on unresolved needs, the functions that could address them, and the conditions required for useful applications.','바이오트릭스는 바이오의약품과 기술 개발을 통해 치료의 가능성을 넓히고자 합니다. 기존 치료로 충분히 해결하지 못한 문제와 이를 해결하는 데 필요한 기능, 실제 적용을 위한 조건을 함께 검토합니다.');
const pages={
index:`<section class="hero review-hero"><div class="hero-image"><img src="/assets/organic-interface.webp" width="1672" height="941" fetchpriority="high" alt="Conceptual image inspired by biomolecular structures" data-alt-en="Conceptual image inspired by biomolecular structures" data-alt-ko="생체분자의 구조에서 영감을 받은 개념 이미지"/></div><div class="wrap hero-inner">${bi('Biopharmaceuticals<br/>and technology<br/><em>for better treatment</em>','바이오의약품과 기술 개발로<br/><em>치료의 가능성을 넓힙니다</em>','h1')}${bi('We focus on problems existing treatments do not adequately address, pursuing technologies that contribute to treatment and quality of life.','기존 치료로 충분히 해결하지 못한 문제에 주목합니다.<br/>환자의 치료와 일상의 삶의 질 향상에 기여할 기술을 추구합니다.','p','hero-copy')}${link('/company','Explore the company','기업 살펴보기')}${bi('Conceptual image inspired by biomolecular structures','생체분자의 구조에서 영감을 받은 개념 이미지','p','hero-caption')}</div></section><section class="wrap section opening"><div>${bi('Our development direction','바이오트릭스의 개발 방향','h2')}</div><div class="editorial-copy">${direction}${bi('We consider clinical relevance alongside performance, safety, production and economics to support wider use of useful technologies.','연구 결과의 임상적 활용 가능성과 성능·안전성·생산 조건을 함께 고려합니다. 기술의 효용과 생산성·경제성을 연결하여 더 많은 사람이 혜택을 누릴 기반을 만들고자 합니다.')}</div></section><section class="project-section"><div class="wrap section"><div class="section-heading">${bi('Research areas','주요 연구 분야','h2')}${bi('Four biological research areas, supported by production and process development','네 가지 생물학 연구 분야와 이를 지원하는 생산·공정 개발','p','section-deck')}</div>${cards()}${bi('These are proposed research and development directions. ACTIVA provides a shared production and process perspective across the areas.','각 분야는 지향하는 연구·개발 방향입니다. 액티바는 분야 전반의 생산·품질·경제성을 검토하는 공통 기반으로 구성했습니다.','p','editorial-note')}</div></section><section class="wrap section">${bi('Development principles','개발 원칙','h2')}${grid()}</section>${cta()}`,
company:intro('Company direction','기업이 추구하는 방향','Biopharmaceutical development, useful technologies and wider access','바이오의약품 개발, 기술의 실용화, 보편적인 접근성')+`<section class="wrap section opening"><div>${bi('Treatment and<br/>quality of life','치료와<br/>삶의 질 향상','h2')}</div><div class="editorial-copy">${direction}${bi('Our long-term ambition is to build a biotechnology company with connected research, development and manufacturing capabilities.','장기적으로 연구·개발·생산 역량을 갖춘 바이오 기업으로 성장하여 치료 선택지와 기술의 활용 범위를 넓히고자 합니다.')}</div></section><section class="wrap section">${bi('Development principles','개발 원칙','h2')}${grid()}</section><section class="founder-band" id="founder"><div class="wrap section opening"><div>${bi('Founder','창업자','h2')}<p class="founder-signature">Yuchan Jeong<span>Founder, BIOTRIX</span></p></div><div class="editorial-copy">${bi('The founding ambition is to build a biotechnology company that contributes to people facing unresolved treatment needs. Reliable production and an accessible cost structure are part of that ambition.','기존 치료로 충분한 도움을 받지 못하는 사람들에게 기여할 바이오 기업을 만들고자 합니다. 기술력과 함께 안정적인 생산, 더 넓은 활용을 뒷받침하는 비용 구조를 갖추는 것이 창업의 지향입니다.')}</div></div></section>${cta()}`,
programs:intro('Research & development directions','연구·개발 방향','Explore each area’s purpose, evaluation needs and next development decisions.','각 분야의 목적과 필요한 검증 역량, 다음 개발 과제를 소개합니다.')+`<div class="wrap program-workspace"><nav class="program-sidebar" aria-label="Research areas">${fields.map((a,i)=>`<a class="program-select" data-program="${a[0]}" href="#${a[0]}"><span>0${i+1}</span><strong>${a[1]}</strong>${bi(a[2],a[3],'small')}</a>`).join('')}</nav><div class="program-content">${fields.map(a=>`<article class="program-panel" id="${a[0]}"><div class="project-masthead"><div><p class="eyebrow">${a[1]}</p>${bi(a[2],a[3],'h2')}</div></div>${bi(a[4],a[5],'p','project-intro')}<div class="project-story"><section>${bi('Focus','주요 기능과 검토 대상','h3')}${bi(a[6],a[7])}</section><section>${bi('Capabilities needed','필요한 검증·개발 역량','h3')}${bi(a[8],a[9])}</section><section>${bi('Next development decisions','다음 개발 과제','h3')}${bi('Define a target problem and candidate material, select evaluation criteria, and identify the expertise needed for collaboration.','대상 문제와 개발 후보를 정하고 평가 기준을 구체화합니다. 이어서 필요한 공동연구·분석·생산 역량을 확인합니다.')}</section></div></article>`).join('')}</div></div><div class="wrap">${bi('The descriptions set out intended directions; specific candidates, experiments and development stages have not been established here.','이 페이지는 연구·개발의 지향을 설명합니다. 구체적인 후보 물질, 실험 수행 현황과 개발 단계는 아직 제시하지 않았습니다.','p','editorial-note')}</div>${cta()}`,
contact:intro('Technology & business collaboration','기술·사업 협력','Joint research, development, production, commercialization and investment proposals','공동연구·기술 개발·생산·사업화·투자 협력 제안')+`<section class="wrap section contact-editorial"><div class="contact-email-block">${bi('Contact BIOTRIX','협력 문의','h2')}<a class="contact-email" href="mailto:andrew@biotrix.co.kr">andrew@biotrix.co.kr</a>${bi('Please include your organization, proposed collaboration, relevant capabilities and contact details.','소속과 제안하시는 협력 내용, 관련 기술·사업 역량, 회신 연락처를 함께 보내 주세요.')}</div><div class="contact-topics">${[['Research & development','연구·기술 개발','Joint research, evaluation and complementary expertise','공동연구, 기능 검증, 상호 보완적인 기술 역량'],['Production & commercialization','생산·사업화','Process development, quality, cost and application opportunities','공정 개발, 품질, 원가와 적용 분야'],['Investment & business partnerships','투자·사업 협력','Long-term development direction and potential business collaboration','장기 개발 방향과 사업 협력 가능성']].map(a=>`<article>${bi(a[0],a[1],'h2')}${bi(a[2],a[3])}</article>`).join('')}</div></section>`};
for(const [name,main]of Object.entries(pages)){const f=path.join(root,name+'.html');let s=fs.readFileSync(f,'utf8').replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${main}</main>`);fs.writeFileSync(f,s);}
// Keep the existing scientific references; replace the abstract introductory copy.
const sf=path.join(root,'science.html');let s=fs.readFileSync(sf,'utf8');s=s.replace(/<section class="wrap page-intro">[\s\S]*?<\/section>/,intro('Scientific basis','과학적 근거와 검토 기준','Research areas and the evidence needed to evaluate development approaches','연구 분야와 개발 접근을 평가하는 데 필요한 근거'));
const evidence=(s.match(/<section class="wrap section evidence"[\s\S]*?<\/section>/)||[''])[0].replace(/<h2 class="bilingual [^"]*">[\s\S]*?<\/h2>/,bi('Selected scientific reviews','주요 참고 문헌','h2'));
s=s.replace(/<main id="main">[\s\S]*?<\/main>/,`<main id="main">${intro('Scientific basis','과학적 근거와 검토 기준','Research areas and the evidence needed to evaluate development approaches','연구 분야와 개발 접근을 평가하는 데 필요한 근거')}<section class="wrap section">${bi('Evaluation framework','기술 검토 기준','h2')}${grid()}${bi('Define the biological target, test the proposed function, and evaluate safety and production requirements in the intended application.','생물학적 대상을 정하고 제안한 기능을 검증합니다. 적용 분야에 맞춰 안전성과 생산 조건을 평가하는 방향입니다.')}</section>${evidence}${cta()}</main>`);fs.writeFileSync(sf,s);
for(const name of ['index','company','science','programs','contact','privacy','terms']){const f=path.join(root,name+'.html');let s=fs.readFileSync(f,'utf8');s=s.replaceAll('Life, with<br/>new possibilities.','Biopharmaceuticals & technology').replaceAll('생명과학으로 여는,<br/>다음 가능성.','바이오의약품과 기술 개발');s=s.replaceAll('20261003-portfolio','20261003-review');s=s.replace(/<\/head>/,'<meta name="robots" content="noindex,nofollow"/></head>');s=s.replace(/data-title-en="[^"]*"/,'data-title-en="BIOTRIX — Review preview"').replace(/data-title-ko="[^"]*"/,'data-title-ko="BIOTRIX — 검토용 프리뷰"').replace(/<title>.*?<\/title>/,'<title>BIOTRIX — Review preview</title>');fs.writeFileSync(f,s);}
fs.appendFileSync(path.join(root,'assets/portfolio.css'),'\n.review-hero .hero-inner{padding-block:100px 55px}.review-hero h1{max-width:1100px;font-size:clamp(2.6rem,5.1vw,5.4rem)}.review-hero h1 em{color:#d6e4ef}.hero-caption{font-size:.75rem;color:#cad7e4;margin:80px 0 0}.review-hero .button{color:white;border-color:#b0c1d1}.principle-grid{margin-top:45px}.project-card h3{margin-bottom:22px}@media(max-width:560px){.review-hero .hero-inner{padding-top:65px}.review-hero h1{font-size:2.7rem!important;line-height:1.3!important}.hero-caption{margin-top:80px}}\n');
console.log('Review preview built');
